# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3479ebaa625733186981b842a4f7fff52c5e88c1d7ba74385a954d4b33d3db6b8cc2409baad3a4ac5f1b5b1d920764866c105a0a7c5511cadf68bd4431c342b

test:
  secret_key_base: eafb77e6c23647d53d6513bbbceb1983aad9e92475ce545605e1cc15472ae16df0fa84fcde7f3d80ff3c977fb167b5613db90d72e4732b2bf37939020a3ee4b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
